/*
 * Twinkle_Twinkle_Little_Star.ino
 * Файл с примером использования библиотеки QBPlay
 * https://en.wikibooks.org/wiki/QBasic/Appendix#PLAY
 *
 * created 10.11.2017
 * modified 12.11.2017
 * with Arduino 1.8.3 (tested on Arduino Uno)
 *
 * Copyright 2017 Vitaliy Fust <aslok.zp@gmail.com>
 *
 * This work is licensed under the MIT License (MIT). To view a copy of this
 * license, visit http://opensource.org/licenses/MIT or send a letter to:
 * Open Source Initiative
 * 855 El Camino Real
 * Ste 13A, #270
 * Palo Alto, CA 94301
 * United States.
 *
 *
 */

#include "QBPlay.h"
QBPlay* play;
const byte speaker_pin = A3;

const char Twinkle_Twinkle_Little_Star[] PROGMEM = "MNT150L32O3CEG>C<GEG>C<EEG>C<GEG>C<C>CEG<G>CEG<E>CEG<G>CEG<C>CFA<A>CFA<F>CFA<A>CFA<C>CEG<G>CEG<E>CEG<G>CEGO2B>B>DF<GB>DF<DB>DF<GB>DF<CG>CE<GG>CE<EG>CE<GG>CEO2G>GB>D<GGB>DO2B>GB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>C<C>CEG<G>CEG<E>CEG<G>CEGO2B>B>DF<GB>DF<DB>DF<GB>DF<CG>CE<GG>CE<EG>CE<GG>CEO2G>GB>D<GGB>DO2B>GB>D<GGB>D<C>CEG<G>CEG<E>CEG<G>CEG<CA>CF<AA>CF<FA>CF<AA>CF<CG>CE<GG>CE<EG>CE<GG>CEO2G>GB>D<GGB>DO2B>GB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>C<C>CEG<G>CEG<E>CEG<G>CEG<C>CFA<A>CFA<F>CFA<A>CFA<C>CEG<G>CEG<E>CEG<G>CEGO2B>B>DF<GB>DF<DB>DF<GB>DF<CG>CE<GG>CE<EG>CE<GG>CEO2G>GB>D<GGB>DO2B>GB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>C<CP1L64GP1EP1GP1C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DFO2B>B>DF<GB>DF<DB>DF<GB>DFO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>CO2B>GB>D<GGB>D<DGB>D<GGB>D<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DF<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DFO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>C<CG>CE<GG>CE<EG>CE<GG>CE<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CEO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>D<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DFO2B>B>DF<GB>DF<DB>DF<GB>DF<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DF<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CEO2B>B>DF<GB>DF<DB>DF<GB>DFO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>DO2B>GB>D<GGB>D<DGB>D<GGB>D<CEG>C<GEG>C<EEG>C<GEG>C<CG>CE<GG>CE<EG>CE<GG>CE<C>CEG<G>CEG<E>CEG<G>CEG<C>CEG<G>CEG<E>CEG<G>CEG<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE<CG>CE<GG>CE<EG>CE<GG>CE";

void setup(){
    play = new QBPlay(speaker_pin);
    play->start((__FlashStringHelper*) Twinkle_Twinkle_Little_Star);
}

void loop(){
    play->touch();
}
