/*
 * Theme_from_The_Sting.ino
 * Файл с примером использования библиотеки QBPlay
 * https://en.wikibooks.org/wiki/QBasic/Appendix#PLAY
 *
 * created 10.11.2017
 * modified 12.11.2017
 * with Arduino 1.8.3 (tested on Arduino Uno)
 *
 * Copyright 2017 Vitaliy Fust <aslok.zp@gmail.com>
 *
 * This work is licensed under the MIT License (MIT). To view a copy of this
 * license, visit http://opensource.org/licenses/MIT or send a letter to:
 * Open Source Initiative
 * 855 El Camino Real
 * Ste 13A, #270
 * Palo Alto, CA 94301
 * United States.
 *
 *
 */

#include "QBPlay.h"
QBPlay* play;
const byte speaker_pin = A3;

const char Theme_from_The_Sting[] PROGMEM = "MNT255L8O4DEC<AABGGDEC<AABGGDEC<AABAG+GGG>G>GG<DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCO2DD+E>CC<E>CC<E>CCCCCCCAGF+A>CEEDC<A>DDDDDDO2DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCCDECDEECDCECDEECDCECDEE<B>DDCCCCCCO2DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCO2DD+E>CC<E>CC<E>CCCCCCCAGF+A>CEEDC<A>DDDDDDO2DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCCDECDEECDCECDEECDCECDEE<B>DDCCCCC<EFF+GGAGGEFF+GGAGGEC<GAB>CDEDCD<G>EFGAGEFGGAGGEFF+GGAGGGAA+BBBBBAF+DGGGGGEFF+GGAGGEFF+GGAGGEC<GAB>CDEDCDCCCCC<GF+G>CC<A>CC<A>C<AG>CEGGEC<GAA>CCEDDCCCCCC>EFF+GGAGGEFF+GGAGGEC<GAB>CDEDCD<G>EFGAGEFGGAGGEFF+GGAGGGAA+BBBBBAF+DGGGGGEFF+GGAGGEFF+GGAGGEC<GAB>CDEDCDCCCCC<GF+G>CC<A>CC<A>C<AG>CEGGEC<GAA>CCEDDCCCCCCCO2DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCO2DD+E>CC<E>CC<E>CCCCCCCAGF+A>CEEDC<A>DDDDDDO2DD+E>CC<E>CC<E>CCCCCC>CDD+ECDEE<B>DDCCCCCCCDECDEECDCECDEECDCECDEE<B>DDCCCCCCO1CCO3AG+AAAA>CCDDDDDDDD<FEFFFFAAA+A+A+A+A+A+A+GDDGDDGDDCCCCFFFFEG+B>DDC<B>C<AAAAA+A+A+A+AG+AAAA>CCDDDDDDDD<FEFFFFAAA+A+A+A+A+A+A+GDDGDDGDDCCCCFFFFA>CC<GGCDEFF<B>CDEFGAG+AAAA>CCDDDDDDDD<FEFFFFAAA+A+A+A+A+A+A+GDDGDDGDDCCCCFFFFEG+B>DDC<B>C<AAAAA+A+A+A+AG+AAAA>CCDDDDDDDD<FEFFFFAAA+A+A+A+A+A+A+GDDGDDGDDCCCCFFFFA>CC<GGCDEFFO1FFO4FFO1FFO3CC<A>CC<A>C<AG>CEGGEC<GAA>CCEDDCCCCC>CCO1CC>FFEFFEFF<F>A>D<A>CDC<AGGF+GGF+GG<GO3CECDEDCDDC+DDC+DDO1DO3FAFGAGF>CCCCCC<AAGG<GGGGGGFFEFFEFF<F>A>D<A>CDC<AGGF+GGF+GG<GO3CECDEDC<AG+A>GGFFCED+EAA>C<GECCCCEDDCCC<GGGGGGFFEFFEFF<F>A>D<A>CDC<AGGF+GGF+GG<GO3CECDEDCDDC+DDC+DDO1DO3FAFGAGF>CCCCCC<AAGG<GGGGGGFFEFFEFF<F>A>D<A>CDC<AGGF+GGF+GG<GO3CECDEDC<AG+A>GGFFCED+EAA>C<GECCCCEDDCCCCC>CC";

void setup(){
    play = new QBPlay(speaker_pin);
    play->start((__FlashStringHelper*) Theme_from_The_Sting);
}

void loop(){
    play->touch();
}
