/*
 * Moonlight_Sonata_3.ino
 * Файл с примером использования библиотеки QBPlay
 * https://en.wikibooks.org/wiki/QBasic/Appendix#PLAY
 *
 * created 10.11.2017
 * modified 12.11.2017
 * with Arduino 1.8.3 (tested on Arduino Uno)
 *
 * Copyright 2017 Vitaliy Fust <aslok.zp@gmail.com>
 *
 * This work is licensed under the MIT License (MIT). To view a copy of this
 * license, visit http://opensource.org/licenses/MIT or send a letter to:
 * Open Source Initiative
 * 855 El Camino Real
 * Ste 13A, #270
 * Palo Alto, CA 94301
 * United States.
 *
 *
 */

#include "QBPlay.h"
QBPlay* play;
const byte speaker_pin = A3;

const char Moonlight_Sonata_3[] PROGMEM = "MNT200L16O1G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EL8G+G+P16L16O1G+>CD+G+CD+G+>C<D+G+>CD+<G+CD+>G+CD+G+>C<D+G+>CD+<G+>CD+L8G+G+L16O2C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+>C+L8C+P16L16O2C+F+A>C+C+F+A>C+C+F+AL8>C+C+P16L16O2C+EG>C+C+EG>C+C+EGL8>C+C+CL16O3G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>GL4G+L2O2G+.P16L16<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+EEG+>C+L8EEP16L16O2EG>C+E<G>C+EGC+EG>C+<EG>C+E<G>C+EGC+EG>C+<EG>C+L8EEP16L16O2D+A+>C+D+<A>C+D+A+C+D+A+>C+<D+A+>C+D+<A+>C+D+A+C+D+A+>C+<A+D+C+A+D+C+<A+L4BL2>D+L8<B.L16G+L32GG+A+L8G+.L4G.L8G>D+.L16<GL4A+G+.L8G+>D+.L16<G+L4BA+.L8A+>D+.L16<A+L8BL4O5D+D+L8D+<BG+G+L4GGL8G>D+<GA+L4G+G+L8G+>D+<G+BL4A+A+L8A+>D+<A+L2>CC+L4<A+L2B.G+AL64FL32G.L16FGFGL2G+.AL16AEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+DED+ED+EC+<BAL2G+L64BL32G+.L16A+G+A+G+A+G+A+L4G+<AL16AEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+DEF+G+AB>C+DFL2E<G+B<GL8G+BBBBBA+G+G>D+D+D+D+D+D+D+D+<BBBBBA+G+G>D+D+D+D+D+D+D+D+D+D+<BP8>EEC+P8D+D+<BP8>D+D+<A+B>BBBBBA+G+G>EEEEED+C+<BBBBBBA+G+G>EEEEED+C+<BBB>D+P8C+C+EP8<BB>D+P8<A+A+>D+P8<BB>D+P8<AA>C+P8<G+G+BP8GGA+L4G+P4P4L8<B.L16G+L4G>D+D+D+L32O2B>G+L8>D+.L2D+L8B.L16G+L4G>D+D+D+L32O3B>G+L8>D+.L4D+L32<C+GL8>D+.L4D+L32O3B>G+L8>D+.L4D+L32<C+GL8>D+.L4D+L16O2B>G+D+G+<B>G+D+G+<B>G+D+G+<B>G+D+G+CF+D+F+CF+D+F+CF+D+F+CF+D+F+EO1G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EL8G+G+P16L16O1G+>CD+G+CD+G+>C<D+G+>CD+<G+CD+>G+CD+G+>C<D+G+>CD+<G+>CD+L8G+G+L16O2C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+L8>C+C+P16L16O2C+F+A>C+C+F+A>C+C+F+AL8>C+C+P16L16O2C+EG>C+C+EG>C+C+EGL8>C+C+CL16O3G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>GL4G+L2O2G+.P16L16<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+EEG+>C+L8EEP16L16O2EG>C+E<G>C+EGC+EG>C+<EG>C+E<G>C+EGC+EG>C+<EG>C+L8EEP16L16O2D+A+>C+D+<A>C+D+A+C+D+A+>C+<D+A+>C+D+<A+>C+D+A+C+D+A+>C+<A+D+C+A+D+C+<A+L4BL2>D+L8<B.L16G+L32GG+A+L8G+.L4G.L8G>D+.L16<GL4A+G+.L8G+>D+.L16<G+L4BA+.L8A+>D+.L16<A+L8BL4O5D+D+L8D+<BG+G+L4GGL8G>D+<GA+L4G+G+L8G+>D+<G+BL4A+A+L8A+>D+<A+L2>CC+L4<A+L2B.G+AL64FL32G.L16FGFGL2G+.AL16AEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+DED+ED+EC+<BAL2G+L64BL32G+.L16A+G+A+G+A+G+A+L4G+<AL16AEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+<BAEF+G+AB>C+DEF+G+AB>C+DFL2E<G+B<GL8G+BBBBBA+G+G>D+D+D+D+D+D+D+D+<BBBBBA+G+G>D+D+D+D+D+D+D+D+D+D+<BP8>EEC+P8D+D+<BP8>D+D+<A+B>BBBBBA+G+G>EEEEED+C+<BBBBBBA+G+G>EEEEED+C+<BBB>D+P8C+C+EP8<BB>D+P8<A+A+>D+P8<BB>D+P8<AA>C+P8<G+G+BP8GGA+L4G+P4P4L8<B.L16G+L4G>D+D+D+L32O2B>G+L8>D+.L2D+L8B.L16G+L4G>D+D+D+L32O3B>G+L8>D+.L4D+L32<C+GL8>D+.L4D+L32O3B>G+L8>D+.L4D+L32<C+GL8>D+.L4D+L16O2B>G+D+G+<B>G+D+G+<B>G+D+G+<B>G+D+G+CF+D+F+CF+D+F+CF+D+F+CF+D+F+E<C+EG+>C+<EG+>C+F<G+>C+FG+C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+L8>C+C+P16L16O2C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+L8>C+C+P16L16O2C+F+A>C+C+F+A>C+C+F+AL8>C+C+P16L16O2C+G+B>C+C+G+B>C+C+G+BL8>C+C+L4C+L2<C+L8<A.L16F+L32FF+G+L8F+.L4F.L8F>C+.L16<FL4G+F+.L8F+>C+.L16<F+L4AG+.L8G+>C+.L16<G+A>C+<A>C+<F+>C+<A>C+<F+>C+<A>C+<F+>C+<A>C+<G+>C+<B>C+<G+>C+<B>C+<G+>C+<B>C+<G+>C+<B>C+<F+>C+<A>C+<F+>C+<A>C+<F+>C+<A>C+<F+>C+<A>C+<F+>D<A>D<F+>D<A>D<A>DCD<A>DCD<G>D<B>D<G>D<B>D<G>D<B>D<G>D<B>D<A>DCD<A>DCD<A>DCD<A>DCD<G>D<B>D<G>D<B>D<G>D<B>D<G>D<B>D<G+>D<B>D<G+>C+<B>C+<G+>C+<B>C+<G+>C+<B>C+<F+>C+<A>C+<F+>C+<A>C+<F+>F+<A>F+<F+>F+<A>F+<F+>F+D+F+<F+>F+D+F+<F+>F+D+F+<F+>F+D+F+<E>EC+E<E>EC+E<E>EC+E<E>EC+E<D+>D+C+D+<D+>D+C+D+<D+>D+C+D+<D+>D+C+D+L4D+L2<G+L8AG+L4F+L8G+F+L4EL8F+EL4D+L8ED+L4C+L8D+C+L2<B>C+L4D+>G+.L8G+AG+F+F+G+F+EEF+ED+D+ED+C+C+D+C+L2CC+L32<CF+L8>D+.L2D+L4C+CCC+C+L32<CF+L8>D+.L2D+L8<E>C+<F+>C<F+>C<E>C+<E>C+<F+>D+<F+>D+<E>C+<E>C+L32O2A>C+D+AL8AL2A.L32<G+>CD+G+L8G+L2G+.P16L16O1G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EL8G+G+P16L16O1G+>CD+G+CD+G+>C<D+G+>CD+<G+>CD+G+CD+G+>C<D+G+>CD+<G+>CD+L8G+G+P16L16O2C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+>C+<FG+>C+F<G+>C+FG+C+FG+L8>C+C+P16L16O2C+F+A>C+C+F+A>C+C+F+AL8>C+C+P16L16O2C+EG>C+C+EG>C+C+EGL8>C+C+CL16O3G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<G+>G+<G+>G+<A+>G+CG+C+G+D+G+CG+D+G+C+G+F+G+EG+D+G+C+G+CG+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>G<G+>G+<A>GL4G+L2O2G+.P4>G+L8E.L16C+L32CC+D+L8C+.L4C.L8CG+.L16CL4D+C+.L8C+G+.L16C+L4ED+.L8D+G+.L16D+L8EL4>G+G+L8G+EC+C+L4CCL8CG+CD+L4C+C+L8C+G+C+EL4D+D+L8D+G+D+L2FF+L16C+D+C+D+L2E.C+DL16<A+>C<A+>CL2C+.DL16D<AB>C+DEF+ED<AB>C+DEF+ED<AB>C+DEF+ED<AB>C+DEF+GAG+BAGF+EDL2C+L64EL32C+.L16D+C+D+C+D+C+D+L4C+<DL16D<AB>C+DEF+ED<AB>C+DEF+ED<AB>C+DEF+G+F+D<AB>C+DEF+GAB>C+DEF+GG+L2AC+E<CL8C+EEEEED+C+CG+G+G+G+G+G+G+G+EEEEED+C+CG+G+G+G+G+G+G+G+G+G+EP16AAF+P16G+G+EP16G+G+D+G+>EEEEED+C+C>CCCCCC+D+E<EEEEED+C+C>CCCCCC+D+EC+C+<G+P16>C+C+<AP16G+G+EP16G+G+D+P16G+G+EP16F+F+DP16EEC+P16D+D+CL4C+P4P4L8<E.L16C+L4CG+G+G+L32<E>C+L8G+.L2G+L8>E.L16C+L4CG+G+G+L32<E>C+L8G+.L4G+L32<F+>CL8G+.L4G+L32<E>C+L8G+.L4G+L32<F+>CL8G+.L4G+L16O2E>C+<G+>C+<E>C+<G+>C+<E>C+<G+>C+<E>C+<G+>C+<F>C+<G+>C+<F>C+<G+>C+<F>C+<G+>C+<F>C+<G+>C+C+<C+F+A>C+<F+A>C+F+<A>C+F+AC+F+A>C+<F+A>C+F+<A>C+F+AC+F+AL8>C+C+L16O2C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+E<G+>C+EG+C+EG+L8>C+C+P16L32O2C+EGA+L4>C+.L32C+EGA+L4>C+L8C+L32C+EGA+L2>C+.P16L32O1A>CD+F+L4A.L32A>CD+F+L4AL16AA>CD+L2A.L16<EC+<A+GEC+EGL32A+.>C+.E.G.A+.>C+.E.G.A+.>C+.<A+.E.L16>E.C+.<G+.E.C+.<G+.>E.C+.<G+.E>C+<G+EC+G+EC+<G+>EC+<G+E>C+<G+EC+G+EC+<G+AA+B>CC+DD+EFF+GG+AA+B>CC+DD+L32E.F.F+.G.G+.A.A+.B.>C.C+.D.D+.E.FF+GG+L1AL16AL32G+F+ED+F+C+CD+<AG+F+AED+F+C+CD+<AG+F+AED+F+C+CD+<AG+L1GG+L4>C+P4P4L8>E.L16C+L4CG+G+G+L32<E>C+L8G+.L2G+L8>E.L16C+L4CG+G+G+L32<E>C+L8G+.L4G+L32<F+>CL8G+.L4G+L32<E>C+L8G+.L4G+L32<F+>CL8G+.L4G+L64<E>C+L32G+L16<EG+>C+E<G+>C+EG+C+EG+>C+<EG+>C+EC+<G+E>C+<G+EC+G+EC+<G+>EC+<G+E>C+<G+EC+G+EC+<G+>EC+<G+E>C+<G+EG+L4C+P4O5C+P4<C+";

void setup(){
    play = new QBPlay(speaker_pin);
    play->start((__FlashStringHelper*) Moonlight_Sonata_3);
}

void loop(){
    play->touch();
}
